# Generated by Django 6.0.6 on 2026-09-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0024_assetdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequestworkflow',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
