# Generated by Django 6.0.6 on 2026-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0027_asset_processor_graphic_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='series_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Returned', 'Returned'), ('Temporary', 'Temporary User')], default='In Use', max_length=50),
        ),
    ]
