# Generated by Django 6.0.6 on 2026-09-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0028_alter_asset_series_number_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='In Use', max_length=50),
        ),
    ]
