# Generated by Django 6.0.6 on 2026-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0030_repair_custom_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procurementrequestinitial',
            name='asset_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Server', 'Server'), ('Software License', 'Software License'), ('Peripheral', 'Peripheral')], max_length=50),
        ),
    ]
