# Generated by Django 6.0.6 on 2026-10-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0031_asset_display_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_app.employee'),
        ),
    ]
